// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SteamManager.Infrastructure.Persistence;

#nullable disable

namespace SteamManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SteamManager.Core.Models.SteamAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AppId")
                        .HasColumnType("int")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int")
                        .HasColumnName("duration_ms");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestSummary")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("request_summary");

                    b.Property<string>("ResponseSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("response_summary");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Source", "Operation");

                    b.ToTable("steam_audit_log", (string)null);
                });

            modelBuilder.Entity("SteamManager.Core.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("api_name");

                    b.Property<int>("AppId")
                        .HasColumnType("int")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionI18n")
                        .HasColumnType("longtext")
                        .HasColumnName("description_i18n");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNameI18n")
                        .HasColumnType("longtext")
                        .HasColumnName("display_name_i18n");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<double>("GlobalPercent")
                        .HasColumnType("double")
                        .HasColumnName("global_percent");

                    b.Property<string>("IconGrayUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("icon_gray_url");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_unlocked");

                    b.Property<int>("UnlockOffsetMinutes")
                        .HasColumnType("int")
                        .HasColumnName("unlock_offset_minutes");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("unlocked_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("GameId", "ApiName")
                        .IsUnique();

                    b.HasIndex("GameId", "IsUnlocked", "UnlockOffsetMinutes");

                    b.ToTable("achievement", (string)null);
                });

            modelBuilder.Entity("SteamManager.Core.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AchievementsCachedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("achievements_cached_at");

                    b.Property<int>("AppId")
                        .HasColumnType("int")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<int?>("DropsRemaining")
                        .HasColumnType("int")
                        .HasColumnName("drops_remaining");

                    b.Property<DateTime?>("LastSessionStart")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_session_start");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("NameI18n")
                        .HasColumnType("longtext")
                        .HasColumnName("name_i18n");

                    b.Property<int?>("ReferencePlayMinutes")
                        .HasColumnType("int")
                        .HasColumnName("reference_play_minutes");

                    b.Property<int>("SavedIdleDeltaMinutes")
                        .HasColumnType("int")
                        .HasColumnName("saved_idle_delta_minutes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<int>("TotalPlayMinutes")
                        .HasColumnType("int")
                        .HasColumnName("total_play_minutes");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.ToTable("game", (string)null);
                });

            modelBuilder.Entity("SteamManager.Core.Models.SteamConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<DateTime>("CreatedAt"));

                    b.Property<string>("DisplayTimezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("UTC")
                        .HasColumnName("display_timezone");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("language");

                    b.Property<string>("PasswordEnc")
                        .HasColumnType("longtext")
                        .HasColumnName("password_enc");

                    b.Property<string>("SessionToken")
                        .HasColumnType("longtext")
                        .HasColumnName("session_token");

                    b.Property<DateTime?>("SessionUpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("session_updated_at");

                    b.Property<string>("SyncCron")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sync_cron");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.Property<string>("WebApiKey")
                        .HasColumnType("longtext")
                        .HasColumnName("web_api_key");

                    b.HasKey("Id");

                    b.ToTable("steam_config", (string)null);
                });

            modelBuilder.Entity("SteamManager.Core.Models.PlayQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("added_at");

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("SavedSessionMinutes")
                        .HasColumnType("int")
                        .HasColumnName("saved_session_minutes");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.HasIndex("SortOrder");

                    b.ToTable("play_queue", (string)null);
                });

            modelBuilder.Entity("SteamManager.Core.Models.Achievement", b =>
                {
                    b.HasOne("SteamManager.Core.Models.Game", "Game")
                        .WithMany("Achievements")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamManager.Core.Models.PlayQueueItem", b =>
                {
                    b.HasOne("SteamManager.Core.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SteamManager.Core.Models.Game", b =>
                {
                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
